### ISSUE TITLE
Issue HTML helper after use requestAction

### ISSUE THREAD

**Issue by huynh05101** [littleant/cakephp-1.3.21#15]
Hi! 
I have a problem. Can you help me to fix it
- In Controller a_controller, call requestAction( b_controller/act)
- In View call $this->Html->url( array( 'action' => 'otherAction')); 
  + In origin Cake 1.3.21, it return url "/a_controller/otherAction/"
  + In this case: It return url: "/b_controller/otherAction"

Could you please help!

Thanks
Huynh Le

**Comment by littleant** [comment]
I could verify the changed behavior.

The cause was that the `$this` variable was set somewhere, and was used in the static method `Router::url()`.
This worked in the PHP 5 version somehow, but after the port to PHP 7 `$this` was not set to the same value anymore.
I hope I didn't miss a deeper root cause.
